name: Release

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: "Derive and set version"
        env:
          TMPDIR: "/home/runner/work/_temp"
        run: |
          git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
          git config --global user.name ${{ secrets.GIT_USER_NAME }}

          # fetch tags
          git fetch --tag &> /dev/null

          # set version
          lastTag=$(git describe --tags $(git rev-list --tags --max-count=1) | sed 's/^v\(.*\)/\1/')
          if [[ -z "$lastTag" ]]; then
            lastTag="v0.0.0"
          fi

          IFS='.' read -r X Y Z <<< "$lastTag"
          X="${X//v/}"    # tag version to pom version
          Z=$((Z+1))
          mvn versions:set -DnewVersion="$X.$Y.$Z" > "$TMPDIR/mvn-version.log"
          echo "Version updated"

          # compile
          mvn compile > "$TMPDIR/mvn-compile.log" || {
            cat "$TMPDIR/mvn-compile.log"
            exit $FILENO
          }

          # checkout milestones branch
          BRANCH_NAME="rel_v$X.$Y.$Z"
          git checkout -b "$BRANCH_NAME"

          # commit
          git add .
          git commit -m "release $X.$Y.$Z"

          # tag
          git tag "v$X.$Y.$Z"

          # push
          git push --set-upstream origin "$BRANCH_NAME" --force
          git push --tags

          # delete branches
          git checkout main
          git push -d origin "$BRANCH_NAME"
          git branch -D "$BRANCH_NAME"
